---
title: "Evolution Of two wtf Gamete Killers"
author: "Jose F. Lopez Hernandez"
output:
  html_document: 
    code_folding: hide
    highlight: tango
    theme: lumen
    always_allow_html: TRUE
    toc: yes
    toc_float: yes
    fig_width: 5.04
    fig_height: 3
  pdf_document:
    toc: yes
    fig_width: 5.04
    fig_height: 3 
editomar_options: 
  chunk_output_type: console
---


```{r, echo=FALSE, message=FALSE,warning=FALSE}
knitr::opts_chunk$set(echo=TRUE, fig.path = "./images.V8/")
source("./bin/system_setup_and_functions.R")
```

# Figure 2
```{r Figure2A, fig.width=6.5,fig.height=3, message=FALSE,warning=FALSE}
gamete.frequencies<-data.frame(x1_init=c(0.01  , 0.1 , 0.5   , 0      ,0     , 0),
                               x2_init=c(0     , 0   , 0     , 0.01   ,0.1   , 0.5),
                               x3_init=c(0     , 0   , 0     , 0      ,0     , 0),
                               x4_init=c(1-0.01,1-0.1, 1-0.5 , 1-0.01 ,1-0.1 ,1-0.5))

t.values<-create.transmission.values(tx.limits =c(0.5,0.5),ty.limits=c(0.5,0.5),step=0.5)

dplyr::tibble(gamete.frequencies)->gamete.frequencies
filter(t.values,tx==ty)->t.values
## Merge frequencies and transmission advantage values.
SameDriverAdvantage.freqs<-merging.frequencies.and.t.values(
  gamete.frequencies=gamete.frequencies,
  transmision.values=filter(t.values))

list.Frequencies<-apply(SameDriverAdvantage.freqs,MARGIN = 1,function(X){
  Simulate.TwoIdenticalDrivers(frequencies = X[c("x1_init","x2_init","x3_init","x4_init")],
                               recombi.freq = c(0),
                               t = X["tx"],generations = 500,
                               break.stable = FALSE)
})
SimulatedFrequencies<-do.call("rbind",list.Frequencies)

SimulatedFrequencies%>%
  mutate(Generations=Generations+1)%>%
    ggplot()+
  xlim(0,2.5)+
  ylim(0,1)+
  ylab("Frequency 2 drivers.With recombination")+
  geom_line(aes(x=log10(Generations),y=F_xPlus_F_XPlus+F_xPlus_F_XMinus,
                group=id,color=id,lty=as.character(tx)),size=1)+
  scale_color_manual(values=c(rep("#E89524",3),
                              rep("#757E34",3)))+
  scale_x_continuous(breaks = seq(0,3,1),labels = seq(0,3,1),n.breaks = 4)+
  #scale_color_gradient2(low ="#D3BA07",mid ="#286894" ,high ="#B7002C",midpoint=0.5)+
  #facet_wrap(~tx)+
  theme(axis.title.x = element_text(size=10),
        legend.justification=c(1,1),
        axis.text.x =  element_text(size=10),
        axis.title.y = element_text(size=10),
        axis.text.y  =  element_text(size=10),
        legend.text = element_text(size=10),
        legend.title = element_text(size=10),
        strip.text = element_blank(),
        legend.key.size = unit(x = 2,units = "line"),
        panel.background =element_rect(fill="gray99"),
        panel.border = element_rect(color="black", size=0.5,fill=NA),
        panel.grid.major.y = element_line(color="gray75", size=0.25),
        panel.grid.major.x = element_line(color="gray75", size=0.25))+ggtitle("Figure 2a")
```

```{r Figure2C,fig.width=6.5, fig.height=6, message=FALSE,warning=FALSE}
gamete.frequencies<-data.frame(x1_init=c(0.03  , 0    ),
                               x2_init=c(0.09   , 0.09  ),
                               x3_init=c(0     , 0.03 ),
                               x4_init=c(1-0.12,1-0.12))

t.values<-create.transmission.values(tx.limits =c(1,1),ty.limits=c(1,1),step=0.05)

dplyr::tibble(gamete.frequencies)->gamete.frequencies
t.values<-t.values
## Merge frequencies and transmission advantage values.
SameDriverAdvantage.freqs<-merging.frequencies.and.t.values(
  gamete.frequencies=gamete.frequencies,
  transmision.values=filter(t.values))

list.Frequencies<-apply(SameDriverAdvantage.freqs,MARGIN = 1,function(X){
  Simulate.TwoIdenticalDrivers(frequencies = X[c("x1_init","x2_init","x3_init","x4_init")],
                               recombi.freq = c(0,0.5),
                               t = X["tx"],generations = 500,
                               break.stable = FALSE)
})
SimulatedFrequencies<-do.call("rbind",list.Frequencies)


  
SimulatedFrequencies%>%
    mutate(Generations=Generations+1)%>%
    ggplot()+
  xlim(0,2)+
  ylim(0,1)+
  ylab("Frequency 2 drivers.With recombination")+
  geom_line(aes(x=log10(Generations),y=F_xPlus_F_XPlus,group=id,color=id),size=1,color="#757E34")+
  geom_line(aes(x=log10(Generations),y=F_xPlus_F_XMinus,group=id,color=id),size=1,color="#E89524")+
  geom_line(aes(x=log10(Generations),y=F_xMinus_F_XPlus,group=id,color=id),size=1,color="#009262")+
  facet_wrap(recombFreq~x1_init)+
  theme(axis.title.x = element_text(size=10),
        legend.justification=c(1,1),
        axis.text.x =  element_text(size=10),
        axis.title.y = element_text(size=10),
        axis.text.y  =  element_text(size=10),
        legend.text = element_text(size=10),
        legend.title = element_text(size=10),
        #strip.text = element_blank(),
        legend.key.size = unit(x = 2,units = "line"),
        panel.background =element_rect(fill="gray99"),
        panel.border = element_rect(color="black", size=0.5,fill=NA),
        panel.grid.major.y = element_line(color="gray75", size=0.25),
        panel.grid.major.x = element_line(color="gray75", size=0.25))+ggtitle("Figure 2b")
```


# Figure 3
```{r Figure_3, fig.width=9,fig.height=4.2, fig.align='center', echo=TRUE,, message=FALSE,warning=FALSE, fig.cap= "Figure 3"}
t<-seq(0,1,0.0025)
tx_ty<-do.call("rbind",sapply(X = t,FUN = function(X){
  list(data.frame(tx=X,ty=t))
  }))
mutate(tx_ty,
       Sp.Surv.Db_Zer=(1/2)*(2+tx*ty-tx-ty),
       Sp.Surv.Single=1+(-tx-ty)/2,
       Tot.Surv  = (Sp.Surv.Db_Zer+Sp.Surv.Single)/2 )->tx_ty

filter(tx_ty,tx%in%c(seq(0,1,0.01)),ty%in%c(seq(0,1,0.01)))%>%
ggplot()+
  geom_tile(aes(x=tx,y=ty,fill=Sp.Surv.Db_Zer,color=Sp.Surv.Db_Zer))+ 
  geom_line(data=filter(tx_ty,near(Sp.Surv.Db_Zer,0.55,tol=0.0001)),aes(x=tx,y=ty),color="gray40")+
  geom_line(data=filter(tx_ty,near(Sp.Surv.Db_Zer,0.70,tol=0.0001)),aes(x=tx,y=ty),color="gray80")+
  geom_line(data=filter(tx_ty,near(Sp.Surv.Db_Zer,0.85,tol=0.0001)),aes(x=tx,y=ty),color="white")+
    xlab("Transmission advantage wtfX, tx")+
  ylab("Transmission advantage wtfY, ty")+
      scale_fill_gradient2(low ="#D7ECDB",mid ="#286894" ,high ="#000000",midpoint = 0.5)+
      scale_color_gradient2(low ="#D7ECDB",mid ="#286894" ,high ="#000000",midpoint = 0.5)+
  coord_cartesian(expand = FALSE,clip="off")+
    theme(axis.title.x = element_text(size=10),
        legend.justification=c(1,1), 
        axis.text.x =  element_text(size=10),
        axis.title.y = element_text(size=10),
        axis.text.y  =  element_text(size=10),
        legend.text = element_text(size=10),
        legend.title = element_text(size=10),
        legend.key.size = unit(x = 2,units = "line"),
        plot.title = element_text(size=11),
        panel.background = element_rect(linewidth = 0.75, color="black"),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank())+
  ggtitle("Figure 3 B") -> Fig.3.B


tx_ty%>%
ggplot()+
  geom_tile(aes(x=tx,y=ty,fill=Sp.Surv.Single,color=Sp.Surv.Single))+
   # geom_line(data=filter(tx_ty,tx%in%seq(0,1,0.25)),aes(x=tx,y=ty,group=tx),color="red")+
    xlab("Transmission advantage wtfX, tx")+
  ylab("Transmission advantage wtfY, ty")+
  scale_fill_gradient2(low ="#D7ECDB",mid ="#286894" ,high ="#000000",midpoint = 0.5)+
      scale_color_gradient2(low ="#D7ECDB",mid ="#286894" ,high ="#000000",midpoint = 0.5)+
  geom_line(data=filter(tx_ty,near(Sp.Surv.Single,0.25,tol=0.0001)),aes(x=tx,y=ty),color="gray40")+
  geom_line(data=filter(tx_ty,near(Sp.Surv.Single,0.50,tol=0.0001)),aes(x=tx,y=ty),color="gray80")+
  geom_line(data=filter(tx_ty,near(Sp.Surv.Single,0.75,tol=0.0001)),aes(x=tx,y=ty),color="white")+
  coord_cartesian(expand = FALSE,clip="off")+
  theme(axis.title.x = element_text(size=10),
        legend.justification=c(1,1), 
        axis.text.x =  element_text(size=10),
        axis.title.y = element_text(size=10),
        axis.text.y  =  element_text(size=10),
        legend.text = element_text(size=10),
        legend.title = element_text(size=10),
        legend.key.size = unit(x = 2,units = "line"),
        plot.title = element_text(size=11),
        panel.background =element_rect(fill="gray98"),
        panel.grid.major.y = element_blank(),
        panel.grid.major.x = element_blank())+
  ggtitle("Figure 3 C")-> Fig.3.C
grid.arrange(Fig.3.B,Fig.3.C, nrow = 1) 
```

# Figure 4

```{r, SimulationsFigure4, echo=FALSE, message=FALSE, eval=TRUE,warning=FALSE}
gamete.frequencies<-create.gamete.frequencies(x1.limits = c(0,1),x2.limits = c(0,1),
                                                    x3.limits = c(0,1),x4.limits =c(0,1),step = 0.05)
t.values<-create.transmission.values(tx.limits =c(0,1),ty.limits=c(0,1),step=0.01)
## Merge frequencies and transmission advantage values.
SameDriverAdvantage.freqs<-merging.frequencies.and.t.values(
  gamete.frequencies=gamete.frequencies,
  transmision.values=dplyr::filter(t.values,tx%in%c(0.02,seq(0,1,.1)),tx==ty))

print("File loaded")
print("Run in parallel picked points")
cores<-20
cl <- makeCluster(cores) #make that many nodes
message(clusterEvalQ(cl, library("dplyr"))) ## Loads package to each node
SimulatedFrequencies.list<-parLapply( X=1:cores,
                                      cl = cl,
                                      recombi.freq = 0,
                                      cores=cores,
                                      fun = Simulate.Evolved.PickedPoints.parallel,
                                      frequencies = SameDriverAdvantage.freqs,
                                      generations=10000,break.stable = TRUE,
                                      rounding.limit=13)
flush.console()
stopCluster(cl)
SimulatedFrequencies<-do.call("rbind",SimulatedFrequencies.list)
```

```{r Figur4A_B, fig.width=7,fig.height=11, fig.align='center', echo=TRUE, , message=FALSE,warning=FALSE, fig.cap= "Figure 3"}
#### Picking the data to be plotted.
dplyr::filter(SimulatedFrequencies,
              tx%in%c(0.02,0.5,1),
              x1_init!=1,
              x2_init!=1,x3_init!=1,x4_init!=1,
              x1_init!=0
              )%>%
  arrange(-tx,-ty)->Selected.Evolved.Points.General

(Selected.Evolved.Points.General)%>%
  dplyr::filter( near(x1_init,0.05,tol=0.0001),
                 near(x2_init,0.4,tol=0.0001),
                 x4_init%in%seq(0,1,.1))%>%
ggplot()+
  geom_line(aes(x=log10(Generations),
                y=F_xPlus_F_yPlus,group=id,color=x4_init),
            size=0.5,lty=1)+
    geom_line(aes(x=log10(Generations),
                y=F_xPlus_F_yMinus,group=id,color=x4_init),
            size=0.5,lty=5)+
facet_grid(~tx,)+
  ylim(c(0,1))+
   scale_color_gradient2(low ="#591145",mid ="#F05934" ,high ="#F7DBC4",midpoint = 0.5,
                          limits=c(min(SimulatedFrequencies$x1_init),max(SimulatedFrequencies$x1_init)))+
    theme(axis.title.x = element_text(size=10),
          legend.justification=c(1,1),
          axis.text.x =  element_text(size=10),
          axis.title.y = element_text(size=10),
          axis.text.y  =  element_text(size=10),
          legend.text = element_text(size=10),
          legend.title = element_text(size=10),
          legend.key.size = unit(x = 2,units = "line"),
          panel.background =element_rect(fill="gray99"),
          panel.border = element_rect(color="black", size=0.5,fill=NA),
          panel.grid.major.y = element_line(color="gray75", size=0.25),
          panel.grid.major.x = element_line(color="gray75", size=0.25),
          strip.background = element_rect(fill="white"),
          strip.text = element_text(size=14))+
  ggtitle("Figure 4A")+ylab("w_X+,w_Y w_X+,w_Y-")->figure.4a

picked<-sort(c(seq(0.05,0.9,0.15),0.1, 0.2,0.25 ,0.3,0.5,0.6,0.7,0.8))
Picked.Conditions<-list(
  x1_init=picked,
  x2_init=picked,
  x3_init=0,
  x4_init=seq(0.1,0.95,.1),
  tx=c(0.02,0.5,1),
  ty=c(0.02,0.5,1))

#XY.10000Gen.SameDriverTransmission.Fate.FinalValues.0r%>%
  SimulatedFrequencies%>%
    dplyr::filter(recombFreq==0,x4_init!=1,x3_init==0)%>%
    select(id)%>%unlist()%>%unname()%>%unique()->IDsToPlot

Ternary.gamete.plot.sampled_frequencies(
  evolution.table=SimulatedFrequencies,
  id.simulations.to.plot=IDsToPlot,
  evolved.picked.points=dplyr::filter(SimulatedFrequencies,
                                      tx%in%c(0.02,0.5,1))%>%arrange(-tx,-ty),
  density=FALSE,
  col.arrow = "tx",
  picked.conditions=Picked.Conditions,
  arrows=TRUE,lines=TRUE,
  points=FALSE,plot.generations = c(0,4),
  color.midpoint = 0.5,
  x.axis.left="F_xPlus_F_yMinus",
  y.axis.top="F_xPlus_F_yPlus",
  z.axis.right="F_xMinus_F_yMinus",
  title="Fig.4.B")->Fig.4.C
grid.arrange(figure.4a,Fig.4.C,heights=c(0.4, 0.6))
```

```{r, message=FALSE,warning=FALSE}
rm(Evolved.PickedPoints,SimulatedFrequencies.list,SameDriverAdvantage.freqs,SimulatedFrequencies)
gc()
flush.console()
```

# Figure 5

```{r, SimulationsForFigure5, echo=TRUE, message=FALSE, eval=TRUE, warning=FALSE}
gamete.frequencies<-create.gamete.frequencies(x1.limits = c(0,1),x2.limits = c(0,1),
                                                    x3.limits = c(0,1),x4.limits =c(0,1),step = 0.05)
t.values<-create.transmission.values(tx.limits =c(0,1),ty.limits=c(0,1),step=0.01)
## Merge frequencies and transmission advantage values.
SameDriverAdvantage.freqs<-merging.frequencies.and.t.values(
  gamete.frequencies=filter(gamete.frequencies,
                            x1_init%in%seq(0,1,0.05),
                            x2_init%in%seq(0,1,0.05),
                            x3_init%in%seq(0,1,0.05),
                            x4_init%in%seq(0,1,0.05)),
  transmision.values=dplyr::filter(t.values,tx%in%c(0.02,seq(0,1,.1)),tx==ty))

set.seed(137)
print("File loaded")
print("Run in parallel picked points")
cores<-20
cl <- makeCluster(cores) #make that many nodes
message(clusterEvalQ(cl, library("dplyr"))) ## Loads package to each node
SimulatedFrequencies.list<-parLapply( X=1:cores,
                                      cl = cl,
                                      recombi.freq = c(0.05,0.25,0.5),
                                      cores=cores,
                                      fun = Simulate.Evolved.PickedPoints.parallel,
                                      frequencies = SameDriverAdvantage.freqs,
                                      generations=10000,break.stable = TRUE,
                                      rounding.limit=13)
flush.console()
stopCluster(cl)
SimulatedFrequencies<-do.call("rbind",SimulatedFrequencies.list)
```

```{r Figure_5A, echo=TRUE, message=FALSE, warning=FALSE, eval=TRUE, fig.width=7.4, fig.height=3, fig.cap=""}
#### Picking the data to be plotted.
dplyr::filter(SimulatedFrequencies,
              tx%in%c(0.02,0.5,1),
              x1_init!=1,
              x2_init!=1,x3_init!=1,x4_init!=1,
              x1_init!=0
              )%>%
  arrange(-tx,-ty)->Selected.Evolved.Points.General

(Selected.Evolved.Points.General)%>%
  dplyr::filter( near(x1_init,0.10,tol=0.0001),
                 near(x2_init,0.4,tol=0.0001),
                 x4_init%in%seq(0,1,.10),
                 near(recombFreq,0.5,tol=0.0001))%>%
ggplot()+
  geom_line(aes(x=log10(Generations),
                y=F_xPlus_F_yPlus,group=id,color=x4_init),
            size=0.5,lty=1)+

    geom_line(aes(x=log10(Generations),
                y=F_xPlus_F_yMinus,group=id,color=x4_init),
            size=0.5,lty=5)+

facet_grid(~tx)+
  ylim(c(0,1))+
   scale_color_gradient2(low ="#591145",mid ="#F05934" ,high ="#F7DBC4",midpoint = 0.5,
                          limits=c(min(SimulatedFrequencies$x1_init),max(SimulatedFrequencies$x1_init)))+
    theme(axis.title.x = element_text(size=10),
          legend.justification=c(1,1),
          axis.text.x =  element_text(size=10),
          axis.title.y = element_text(size=10),
          axis.text.y  =  element_text(size=10),
          legend.text = element_text(size=10),
          legend.title = element_text(size=10),
          legend.key.size = unit(x = 2,units = "line"),
          panel.background =element_rect(fill="gray99"),
          panel.border = element_rect(color="black", size=0.5,fill=NA),
          panel.grid.major.y = element_line(color="gray75", size=0.25),
          panel.grid.major.x = element_line(color="gray75", size=0.25),
          strip.background = element_rect(fill="white"),
          strip.text = element_text(size=14))+
  ggtitle("Figure 5A")+ylab("w_X+,w_Y w_X+,w_Y-")->Figure5.A
```

```{r, Figure_5B,message=FALSE, warning=FALSE}
picked<-sort(c(seq(0.05,0.9,0.15),0.1, 0.2,0.25 ,0.3,0.5,0.6,0.7,0.8))
Picked.Conditions<-list(
  x1_init=0.25,
  x2_init=picked,
  x3_init=0,
  x4_init=seq(0.1,0.95,.1),
  tx=c(0.02,0.5,1),
  ty=c(0.02,0.5,1))
SimulatedFrequencies%>%
  dplyr::filter(recombFreq==0.5,x4_init!=1,x3_init==0)%>%
    select(id)%>%unlist()%>%unname()%>%unique()->IDsToPlot

Ternary.gamete.plot.sampled_frequencies(
  evolution.table=SimulatedFrequencies,
  id.simulations.to.plot =IDsToPlot,
  evolved.picked.points=dplyr::filter(SimulatedFrequencies,
                                      recombFreq==0.5,
                                      tx%in%c(0.02,0.5,1)),
  density=FALSE,
  col.arrow = "tx",
  picked.conditions=Picked.Conditions,
  arrows=TRUE,lines=TRUE,
  points=FALSE,plot.generations = c(0,6),
  color.midpoint = 0.5,
  x.axis.left="F_xPlus_F_yMinus+F_xMinus_F_yPlus",
  y.axis.top="F_xPlus_F_yPlus",
  z.axis.right="F_xMinus_F_yMinus",
  title="Figure 5B")->Figure.5.B
```

```{r,  SimulationsForFigure5.C_F, , echo=TRUE, message=FALSE, eval=TRUE,warning=FALSE}
gamete.frequencies<-create.gamete.frequencies(x1.limits = c(0,1),x2.limits = c(0,0),
                                                    x3.limits = c(0,0),x4.limits =c(0,1),step = 0.05)
t.values<-create.transmission.values(tx.limits =c(0,1),ty.limits=c(0,1),step=0.01)
dplyr::filter(t.values,tx%in%as.double(seq(0,1,0.1)))%>%
  dplyr::filter(ty%in%as.double(seq(0,1,0.1)))->t.values


set.seed(137)
## Merge frequencies and transmission advantage values.
SameDriverAdvantage.freqs<-merging.frequencies.and.t.values(
  gamete.frequencies=gamete.frequencies,
  transmision.values=dplyr::filter(t.values,tx==ty))

print("File loaded")
print("Run in parallel picked points")
cores<-2
cl <- makeCluster(cores) #make that many nodes
message(clusterEvalQ(cl, library("dplyr")))
SimulatedFrequencies.list.difRecfreq<-parLapply( X=1:cores,
                                      cl = cl,
                                      recombi.freq =seq(0,0.5,0.1),
                                      cores=cores,
                                      fun = Simulate.Evolved.PickedPoints.parallel,
                                      frequencies = SameDriverAdvantage.freqs,
                                      generations=10000,break.stable = TRUE,
                                      rounding.limit=13)

flush.console()
stopCluster(cl)
SimulatedFrequencies<-do.call("rbind",SimulatedFrequencies.list.difRecfreq)
```

```{r, Figure_5.C_F, message=FALSE, eval=TRUE, fig.width=5.5, fig.height=5.5}
dplyr::filter(SimulatedFrequencies,x3_init==0,x2_init==0,tx%in%c(0.2,1.0),recombFreq%in%c(0,0.5))%>%
  ggplot()+
  geom_path(aes(x=log10(Generations), y=F_xPlus_F_yPlus,color=x1_init,group=x1_init),
            size=.3,alpha = 1,arrow=arrow(type = "closed",length = unit(.05,"cm")))+
  facet_grid(recombFreq~tx)+
  scale_x_continuous(breaks = seq(0,3,1), labels = seq(0,3,1), limits = c(0,3) )+
    scale_color_gradient2(low ="#591145",mid ="#F05934" ,high ="#F7DBC4",midpoint = 0.5,limits=c(0,1))+
    theme(axis.title.x = element_text(size=10),
          legend.justification=c(1,1),
          axis.text.x =  element_text(size=10),
          axis.title.y = element_text(size=10),
          axis.text.y  =  element_text(size=10),
          legend.text = element_text(size=10),
          legend.title = element_text(size=10),
          panel.border = element_rect(color="black", size=0.15,fill=NA),
          legend.key.size = unit(x = 2,units = "line"),
          panel.background =element_rect(fill="gray99"),
          panel.grid.major.y = element_line(color="gray75", size=0.15),
          panel.grid.major.x = element_line(color="gray75", size=0.15),
          strip.background = element_rect(fill="white"),
          strip.text = element_text(size=14),
          legend.position="none",
        strip.placement = "outside")+
  xlab("log10(Generations)")+ylab("wtfX+,wtfY+")+
  ggtitle("Figure.5C-F")->Figure.5CF

#ggtern::grid.arrange(Figure5.A,Figure.5.B,Figure.5CF, nrow = 2,ncol=2)
gl<-list(Figure5.A,Figure.5.B,Figure.5CF)
ggtern::grid.arrange(
  grobs = gl,
  widths = c(2, 1),
  layout_matrix = rbind(c(1, 1),
                        c(2, 3))
)
```

```{r}
rm(SimulatedFrequencies,SimulatedFrequencies.list,
   SimulatedFrequencies.list.difRecfreq,
   SameDriverAdvantage.freqs,SameDriverAdvantage.freqs)
gc()
```

# Figure 6
```{r, Figure6ASimulations,message=FALSE, warning=FALSE}
gamete.frequencies<-create.gamete.frequencies(x1.limits = c(0,1),x2.limits = c(0,1),
                                                    x3.limits = c(0,1),x4.limits =c(0,1),step = 0.1)
t.values<-create.transmission.values(tx.limits =c(0,1),ty.limits=c(0,1),step=0.025)


dplyr::filter(gamete.frequencies,
              x1_init!=1,
              x2_init!=1,
              x3_init!=1,
              x4_init!=1#,
              #x1_init!=0
              )->gamete.frequencies


set.seed(17678)
DifferentDriverAdvantage.freqs_sampled<-merging.frequencies.and.t.values(
 # gamete.frequencies=sample_n(gamete.frequencies,round(406400/5),replace=FALSE)%>%
  gamete.frequencies=gamete.frequencies,
  #transmision.values=dplyr::filter(t.values,tx!=0,ty!=0)%>%sample_n(5000))
  transmision.values=dplyr::filter(t.values,tx!=0,ty!=0))


print("File loaded")
print("Run in parallel picked points")
cores<-20
cl <- makeCluster(cores) #make that many nodes
message(clusterEvalQ(cl, library("dplyr"))) ## Loads package to each node
set.seed(333)
Evolved.PickedPoints.list.r0<-parLapply( X=1:cores,
                                      cl = cl,
                                      recombi.freq =seq(0,0.5,0.25),
                                      cores=cores,
                                      fun = Simulate.Evolved.PickedPoints.parallel,
                                      frequencies = sample_n(DifferentDriverAdvantage.freqs_sampled,10000),
                                      generations=10000,break.stable = TRUE,
                                      rounding.limit=13)

flush.console()
stopCluster(cl)
SimulatedFrequencies<-do.call("rbind",Evolved.PickedPoints.list.r0)
```

```{r, Figure6.A,message=FALSE, warning=FALSE}
set.seed(38948)
dplyr::filter(SimulatedFrequencies,
              x1_init!=1,x2_init!=1,x3_init!=1,x4_init!=1,
              near(x1_init,0.1,tol=0.0001),
              near(x2_init,0.4,tol=0.0001),
              x4_init%in%seq(0,1,.1),
              recombFreq%in%seq(0,0.5,0.25),
              tx%in%sort(sample(seq(0.01,1,0.01),75)),
              ty%in%sort(sample(seq(0.01,1,0.01),75)))%>%
              select(id)%>%
              unique()%>%
              sample_n(25)%>%unlist()->unique.sampled.ids

filter(SimulatedFrequencies,id%in%unique.sampled.ids)%>%
  ggplot()+
  geom_line(aes(x=log10(Generations), y=F_xPlus_F_yPlus,color=x4_init,group=id),
            size=.25,alpha = 1)+
    geom_line(aes(x=log10(Generations), y=F_xPlus_F_yMinus,color=x4_init,group=id),
            size=.25,alpha = 1,lty=5)+
  facet_grid(~recombFreq)+
  scale_x_continuous(breaks = seq(0,4,1), labels = seq(0,4,1), limits = c(0,4) )+
  scale_color_gradient2(low ="#591145",mid ="#F05934" ,high ="#F7DBC4",midpoint = 0.5,
                          limits=c(min(SimulatedFrequencies$x1_init),
                                   max(SimulatedFrequencies$x1_init)))+
    theme(axis.title.x = element_text(size=10),
          legend.justification=c(1,1),
          axis.text.x =  element_text(size=10),
          axis.title.y = element_text(size=10),
          axis.text.y  =  element_text(size=10),
          legend.text = element_text(size=10),
          legend.title = element_text(size=10),
        legend.key.size = unit(x = 2,units = "line"),
        panel.background =element_rect(fill="gray99"),
        panel.grid.major.y = element_line(color="gray85"),
        panel.grid.major.x = element_line(color="gray85"),
        strip.background = element_blank(),
        panel.border = element_rect(color="black", size=0.5,fill=NA),
        strip.text = element_text(size=14))+
  xlab("log10(Generations)")+ylab("wtfX+,wtfY+")+
  ggtitle("Figure 6A")->Figure6.A
Figure6.A
```

```{r, Simulations.Figure6B,message=FALSE, warning=FALSE}
set.seed(1678)
gamete.frequencies<-create.gamete.frequencies(x1.limits = c(0,1),x2.limits = c(0,1),
                                                    x3.limits = c(0,1),x4.limits =c(0,1),step = 0.01)
gamete.frequencies%>%filter( x1_init!=1,x2_init!=1,x3_init!=1,x4_init!=1)%>%
  filter((x1_init+x2_init)!=0,(x1_init+x2_init)!=0)%>%
  dplyr::sample_n(35355,replace=FALSE)->gamete.frequencies.samp

#t.values<-create.transmission.values(tx.limits =c(0.01,1),ty.limits=c(0.01,1),step=0.01)

 create.transmission.values(tx.limits =c(0.01,1),ty.limits=c(0.01,1),step=0.01)%>%
   filter(tx!=ty)%>%
   dplyr::sample_n(5000,replace=FALSE)->t.values.samp

set.seed(137)
DifferentDriverAdvantage.freqs_sampled<-merging.frequencies.and.t.values(
  gamete.frequencies=gamete.frequencies.samp,
  transmision.values=dplyr::filter(t.values.samp,tx!=0,ty!=0))

print("Total simulated conditions")
nrow(DifferentDriverAdvantage.freqs_sampled)

print("File loaded")
print("Run in parallel picked points")
cores<-30
cl <- makeCluster(cores) #make that many nodes
message(clusterEvalQ(cl, library("dplyr"))) ## Loads package to each node
set.seed(333)
Evolved.PickedPoints.list.r0<-parLapply( X=1:cores,
                                      cl = cl,
                                      recombi.freq =seq(0,0.5,0.1),
                                      cores=cores,
                                      fun = Simulate.Evolved.PickedPoints.parallel,
                                      frequencies = sample_n(DifferentDriverAdvantage.freqs_sampled,10000),
                                      generations=10000,break.stable = TRUE,
                                      rounding.limit=13)
flush.console()
stopCluster(cl)
SimulatedFrequencies<-do.call("rbind",Evolved.PickedPoints.list.r0)

filter(SimulatedFrequencies,
       x1_init!=1,x2_init!=1,x3_init!=1,x4_init!=1)->
  All.Present.Evolved

All.Present.Evolved%>%
  mutate(DriverXFreq=F_xPlus_F_yPlus+F_xPlus_F_yMinus,
         DriverYFreq=F_xPlus_F_yPlus+F_xMinus_F_yPlus)->All.Present.Evolved

All.Present.Evolved%>%
  mutate(DriverXFreq.round=round(DriverXFreq,digits = 13),
         DriverYFreq.round=round(DriverYFreq,digits = 13))->All.Present.Evolved

filter(All.Present.Evolved,(DriverYFreq.round==1) | (DriverXFreq.round==1))->All.Present.Evolved.Fixed

select(All.Present.Evolved.Fixed,id)%>%unique()%>%sample_n(10000)%>%unlist()%>%unname()->sampled.ids

FirstFixedRecord<-c()
for(k.ids in 1:10){
  #print(k.ids)
  chunk.ids<-sampled.ids[((k.ids-1)*1000+1):((k.ids*1)*1000)]
  filter(All.Present.Evolved.Fixed,id%in%chunk.ids)->All.Present.Evolved.id.Selected
  FirstFixedRecord.temp<-sapply(chunk.ids,function(X){
      selected.id<-All.Present.Evolved.id.Selected[All.Present.Evolved.id.Selected$id==X,]
      MinX<-selected.id[which(near(selected.id$DriverXFreq,1,tol = 10e-3))[1],"Generations"]
      MinY<-selected.id[which(near(selected.id$DriverYFreq,1,tol = 10e-3))[1],"Generations"]
      list(cbind(data.frame(min.Gen.X.Fixed=MinX,min.Gen.Y.Fixed=MinY),
                 selected.id[1,c("x1_init","x2_init","x3_init","x4_init","recombFreq","tx","ty")]))
    })
  FirstFixedRecord<-c(FirstFixedRecord,FirstFixedRecord.temp)
}
do.call("rbind",FirstFixedRecord)->FirstFixedRecord.DF
```

```{r, Figure6.B,message=FALSE, warning=FALSE}
FirstFixedRecord.DF%>%
ggplot(aes(x=log10((x1_init+x2_init)/(x1_init+x3_init)),y=log10(min.Gen.X.Fixed/min.Gen.Y.Fixed),color=log10(tx/ty)))+
  geom_point(size=0.3)+
    ylim(-2.1,2.1)+
    geom_smooth( color = "black",size=0.7)+
    scale_color_gradient2(low ="#2D2D88",mid ="#CF407D" ,high ="#F3E305",midpoint = 0,limits=c(log10(0.005),log10(1/0.005)))+
    theme(axis.title.x = element_text(size=10),
          legend.justification=c(1,1),
          axis.text.x =  element_text(size=10),
          axis.title.y = element_text(size=10),
          axis.text.y  =  element_text(size=10),
          legend.text = element_text(size=10),
          legend.title = element_text(size=10),
        legend.key.size = unit(x = 2,units = "line"),
        panel.background =element_rect(fill="gray99"),
        panel.grid.major.y = element_line(color="gray85"),
        panel.grid.major.x = element_line(color="gray85"),
        strip.background = element_blank(),
        panel.border = element_rect(color="black", size=0.5,fill=NA),
        strip.text = element_text(size=14))+ggtitle("Figure 6B")->Figure6.B
Figure6.B

FirstFixedRecord.DF%>%
ggplot(aes(x=log10((x1_init+x2_init)/(x1_init+x3_init)),y=log10(min.Gen.X.Fixed/min.Gen.Y.Fixed),color=log10(tx/ty)))+
  #geom_point(size=0.3)+
    #ylim(-2.1,2.1)+
    geom_smooth(aes(color = recombFreq,group=recombFreq),size=0.7)+
    #scale_color_gradient2(low ="#2D2D88",mid ="#CF407D" ,high ="#F3E305",midpoint = 0,limits=c(log10(0.005),log10(1/0.005)))+
    scale_fill_gradient2(low ="#2D2D88",mid ="#CF407D" ,high ="#F3E305",midpoint = 0.25)+
    theme(axis.title.x = element_text(size=10),
          legend.justification=c(1,1),
          axis.text.x =  element_text(size=10),
          axis.title.y = element_text(size=10),
          axis.text.y  =  element_text(size=10),
          legend.text = element_text(size=10),
          legend.title = element_text(size=10),
        legend.key.size = unit(x = 2,units = "line"),
        panel.background =element_rect(fill="gray99"),
        panel.grid.major.y = element_line(color="gray85"),
        panel.grid.major.x = element_line(color="gray85"),
        strip.background = element_blank(),
        panel.border = element_rect(color="black", size=0.5,fill=NA),
        strip.text = element_text(size=14))+ggtitle("Figure 6B.alt")->Figure6.B.alt
Figure6.B.alt
```

```{r,message=FALSE, warning=FALSE}
rm(Evolved.PickedPoints.list.r0,SimulatedFrequencies,DifferentDriverAdvantage.freqs_sampled)
gc()
```



# Figure 7

```{r SimulationsFigure7,message=FALSE, warning=FALSE}
set.seed(1678)
gamete.frequencies<-create.gamete.frequencies(x1.limits = c(0,0),x2.limits = c(0,1),
                                                    x3.limits = c(0,1),x4.limits =c(0,0),step = 0.01)
t.values<-create.transmission.values(tx.limits =c(0,1),ty.limits=c(0,1),step=0.001)


create.transmission.values(tx.limits =c(0,1),ty.limits=c(0,1),step=0.0025)%>%
  dplyr::sample_n(10000,replace=FALSE)->t.values


set.seed(137)
## Merge frequencies and transmission advantage values.
DifferentDriverAdvantage.freqs<-merging.frequencies.and.t.values(
  gamete.frequencies=gamete.frequencies,
  transmision.values=dplyr::filter(t.values,tx!=ty))

print("File loaded")
print("Run in parallel picked points")
cores<-20
cl <- makeCluster(cores) #make that many nodes
message(clusterEvalQ(cl, library("dplyr"))) ## Loads package to each node
Evolved.PickedPoints.list<-parLapply( X=1:cores,
                                      cl = cl,
                                      recombi.freq =0,
                                      cores=cores,
                                      fun = Simulate.Evolved.PickedPoints.parallel,
                                      frequencies = sample_n(DifferentDriverAdvantage.freqs,100000),
                                      generations=10000,break.stable = FALSE,
                                      rounding.limit=13)
flush.console()
stopCluster(cl)
Evolved.PickedPoints<-do.call("rbind",Evolved.PickedPoints.list)
```

```{r Figure7A, echo=TRUE, message=FALSE, warning=FALSE, eval=TRUE, fig.width=5, fig.height=3, fig.cap= ""}
new.gamete.frequencies<-data.frame(x1_init=0, x2_init=seq(0,1,0.0025), x3_init=1-seq(0,1,0.0025), x4_init=0)
new.t.values<-data.frame(tx=sort(rep(seq(0,1,0.005),201)),ty=seq(0,1,0.005))
FrequenciesAntTValues<-merging.frequencies.and.t.values(
  gamete.frequencies=dplyr::filter(new.gamete.frequencies,x2_init!=1,x3_init!=1,x1_init==0,x4_init==0),
  transmision.values=dplyr::filter(new.t.values,tx!=0,ty!=0))
dplyr::filter(FrequenciesAntTValues,near(x2_init,(ty)/(tx+ty),tol=0.00000001),tx+ty!=0)->No.changeX2_X3.to.evolve

No.changeX2_X3.to.evolve%>%
  ggplot(aes(x=log10(tx/ty),y=x2_init))+
  geom_line(size=1)+
  geom_ribbon(ymin=-Inf, aes(ymax=x2_init), fill='#076844', alpha=0.2) +
  geom_ribbon(aes(ymin=x2_init), ymax=Inf, fill='#E89624', alpha=0.2) +
  xlab("log10(tx/ty)")+
  ylab("Min.Freq.toSpread WtfX+")+
  scale_color_gradient2(low ="#2D2D88",mid ="#CF407D" ,high ="#F3E305",midpoint =0,limits=c(log(1/200),log10(200)))+
  scale_y_continuous(breaks = seq(0,1,0.25),labels =seq(0,1,0.25),n.breaks = 5)+
  coord_cartesian( ylim =c(0,1),
                    expand = FALSE) +
    theme(
      legend.justification=c(1,1),
        axis.text.x =  element_text(size=11),
        axis.text.y  =  element_text(size=11),
        axis.title.x = element_text(size=14),
        axis.title.y = element_text(size=14),
        legend.text = element_text(size=11),
        legend.title = element_text(size=11),
        legend.key.size = unit(x = 2,units = "line"),
        panel.background =element_rect(fill="gray99"),
        panel.grid.major.y = element_line(color="gray85"),
        panel.grid.major.x = element_line(color="gray85"),
        strip.background = element_blank(),
        panel.border = element_rect(color="black", size=0.5,fill=NA),
        strip.text = element_text(size=14),
        strip.placement = "outside")+
  ggtitle("Figure7A")->Figure.7A
```

```{r,Figure_7B, echo=TRUE, message=FALSE, warning=FALSE, eval=TRUE, fig.width=10.4, fig.height=3, fig.cap=""}
new.gamete.frequencies<-data.frame(x1_init=0, x2_init=seq(0,1,0.0025), x3_init=1-seq(0,1,0.0025), x4_init=0)
new.t.values<-data.frame(tx=sort(rep(seq(0,1,0.005),201)),ty=seq(0,1,0.005))
FrequenciesAntTValues<-merging.frequencies.and.t.values(
  gamete.frequencies=dplyr::filter(new.gamete.frequencies,x2_init!=1,x3_init!=1,x1_init==0,x4_init==0),
  transmision.values=dplyr::filter(new.t.values,tx!=0,ty!=0))
dplyr::filter(FrequenciesAntTValues,near(x2_init,(ty)/(tx+ty),tol=0.000000001),tx+ty!=0)->No.changeX2_X3.to.evolve

Evolved.PickedPoints%>%
  dplyr::filter(x1_init==0,x2_init!=1,
           x3_init!=1,x4_init==0,
           x2_init%in%c(0.29),
           tx!=c(0.925),
           (x2_init>=(ty/(tx+ty)) | x3_init>=(tx/(tx+ty))),
            near(x2_init,ty/(tx+ty),tol=0.001),
         tx!=0,ty!=0)->Filtered.0r

dplyr::filter(Filtered.0r,Generations==1)%>%
  mutate(logVal=log10(tx/ty),
         val=tx/ty,
         limit=log10(1/x2_init-1))%>%arrange(x2_init,logVal)%>%select(x2_init,x3_init,tx,ty,logVal,limit)



dplyr::filter(Filtered.0r)%>%
  ggplot()+
  geom_path(aes(x=log10(Generations), y=F_xPlus_F_yMinus,color=log10(tx/ty),group=id),
            size=.25,alpha = 1,arrow=arrow(type = "closed",length = unit(.05,"cm")))+
        scale_color_gradientn(colors = c("#2D2D88","#CF407D","#F3E305"),
                              limits=c(-2.2989,2.2989))+
  facet_wrap(~x2_init)+
     theme(
      legend.justification=c(1,1),
        axis.text.x =  element_text(size=11),
        axis.text.y  =  element_text(size=11),
        axis.title.x = element_text(size=14),
        axis.title.y = element_text(size=14),
        legend.text = element_text(size=11),
        legend.title = element_text(size=11),
        legend.key.size = unit(x = 2,units = "line"),
        panel.background =element_rect(fill="gray99"),
        panel.grid.major.y = element_line(color="gray85"),
        panel.grid.major.x = element_line(color="gray85"),
        strip.background = element_blank(),
        panel.border = element_rect(color="black", size=0.5,fill=NA),
        strip.text = element_text(size=14),
        strip.placement = "outside")+
  xlab("log10(Generations)")+ylab("wtfX+,wtfY-")+
  ggtitle("Figure7B")->Figure.7B
log10(Filtered.0r$tx/Filtered.0r$ty)%>%unique()
```

```{r,message=FALSE, warning=FALSE}
rm(Evolved.PickedPoints,Evolved.PickedPoints.list)
gc()
```

```{r,Figure_7B-C_SourceData,echo=TRUE, message=FALSE, warning=FALSE, eval=TRUE, fig.width=6.4, fig.height=3, fig.cap= ""}
Generations=1:10000
x_1=x_2=x_3=x_4=1/4
print("n=4,x_1=x_2=x_3=x_4=1/n")
t1=0.85;t2=0.84;t3=0.22;t4=0.32
print("t1=0.85;t2=0.84;t3=0.22;t4=0.32;")

xs<-c(x_1,x_2,x_3,x_4)
ts<-c(t1,t2,t3,t4)
freqs.table<-CalculateWTFTransCompetitionFourVariants(x.s = rep((1/4),4),t.s = ts,
                                                      generations = 10000,break.stable=TRUE)
melt(freqs.table,value.name = "Frequency",id.vars = "Generations",
     measure.vars = c("x1","x2","x3","x4"))%>%
  ggplot()+
  ylim(c(0,1))+
  xlim(c(0,25))+
  geom_line(aes(x=Generations,y=Frequency,group=variable,color=variable),size=1)+
    geom_line(data=freqs.table,
            mapping = aes(x=Generations,y=MeanPopFitness),color="black",size=2,lty=2,alpha=0.95)+
   scale_color_manual(values = c(x1="#B355A0",x2="#78CDCE",x3="#E12027",x4="#4EAF49"))+
    theme(axis.title.x = element_text(size=10),
          legend.justification=c(1,1),
          axis.text.x =  element_text(size=10),
          axis.title.y = element_text(size=10),
          axis.text.y  =  element_text(size=10),
          legend.text = element_text(size=10),
          legend.title = element_text(size=10),
        legend.key.size = unit(x = 2,units = "line"),
        panel.background =element_rect(fill="gray99"),
        panel.grid.major.y = element_line(color="gray85"),
        panel.grid.major.x = element_line(color="gray85"),
        strip.background = element_blank(),
        panel.border = element_rect(color="black", size=0.5,fill=NA),
        strip.text = element_text(size=14))+
  ggtitle("Figure 7C")->Figure.7C
```

```{r, Figure7D.FourDriversDistribution, fig.width=8, fig.height=9,message=FALSE, warning=FALSE}
TwoDriverAllels<-fate.up.to.four.driver.alleles(n.drivers=2,
                                                generations=50000,
                                                populations=10000,
                                                break.stable=TRUE)

ThreeDriverAlleles<-fate.up.to.four.driver.alleles(n.drivers=3,
                                                generations=50000,
                                                populations=10000,
                                                break.stable=TRUE)

FourDriverAlleles<-fate.up.to.four.driver.alleles(n.drivers=4,
                                                generations=50000,
                                                populations=10000,
                                                break.stable=TRUE)

median(TwoDriverAllels$t)
median(ThreeDriverAlleles$t)
median(FourDriverAlleles$t)


rbind(TwoDriverAllels,ThreeDriverAlleles,FourDriverAlleles)%>%
  select(n.alleles,t) %>%
ggplot(aes(x = t,
           colour=as.character(n.alleles),
           fill=as.character(n.alleles),
           group=as.character(n.alleles))) +
 geom_density(alpha=.2) +
  geom_vline(aes(xintercept=median(TwoDriverAllels$t)), linetype="dashed",color="#999999")+
  geom_vline(aes(xintercept=median(ThreeDriverAlleles$t)), linetype="dashed",color="#CC79A7")+
  geom_vline(aes(xintercept=median(FourDriverAlleles$t)), linetype="dashed",color="#56B4E9")+
scale_fill_manual(values = c("#999999","#D55E00","#56B4E9"))+
   scale_color_manual(values = c("#999999","#D55E00","#56B4E9"))+
  theme(
      legend.justification=c(1,1),
        axis.text.x =  element_text(size=11),
        axis.text.y  =  element_text(size=11),
        axis.title.x = element_text(size=14),
        axis.title.y = element_text(size=14),
        legend.text = element_text(size=11),
        legend.title = element_blank(),
        legend.key.size = unit(x = 2,units = "line"),
        panel.background =element_rect(fill="gray99"),
        panel.grid.major.y = element_line(color="gray85"),
        panel.grid.major.x = element_line(color="gray85"),
        strip.background = element_blank(),
        panel.border = element_rect(color="black", size=0.5,fill=NA),
        strip.text = element_text(size=14),
        strip.placement = "outside")+ggtitle("Figure 7D")->plot.all.t
gridExtra::grid.arrange(Figure.7A,Figure.7B,Figure.7C,plot.all.t,ncol=2)
```

```{r, echo=FALSE}
print("transmissions that are represented as half as often at t>0.9")
rbind(TwoDriverAllels,ThreeDriverAlleles,FourDriverAlleles)->all.drivers

hist(TwoDriverAllels$t,250,plot = FALSE)->two.driv.values
print("Two drivers")
mean(two.driv.values$breaks[near(two.driv.values$density,
     mean(two.driv.values$density[two.driv.values$mids>0.9])/2,tol = 0.025)])

hist(ThreeDriverAlleles$t,250,plot = FALSE)->three.driv.values
print("Three drivers")
mean(three.driv.values$breaks[near(three.driv.values$density,
     mean(three.driv.values$density[three.driv.values$mids>0.9])/2,tol = 0.025)])

hist(FourDriverAlleles$t,250,plot = FALSE)->four.driv.values
print("Four drivers")
mean(four.driv.values$breaks[near(four.driv.values$density,
     mean(four.driv.values$density[four.driv.values$mids>0.9])/2,tol = 0.025)])
```
